// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	"time"
	account_model "user-wallet-service/internal/model/account-model"
	session_model "user-wallet-service/internal/model/session-model"
	user_model "user-wallet-service/internal/model/user-model"
	"user-wallet-service/internal/service/auth-service"
)

// Ensure, that UserRepositoryMock does implement auth_service.UserRepository.
// If this is not the case, regenerate this file with moq.
var _ auth_service.UserRepository = &UserRepositoryMock{}

// UserRepositoryMock is a mock implementation of auth_service.UserRepository.
//
//	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
//		// make and configure a mocked auth_service.UserRepository
//		mockedUserRepository := &UserRepositoryMock{
//			CreateFunc: func(ctx context.Context, user *user_model.User) error {
//				panic("mock out the Create method")
//			},
//			ExistsByEmailFunc: func(ctx context.Context, email string) (bool, error) {
//				panic("mock out the ExistsByEmail method")
//			},
//			FindByEmailFunc: func(ctx context.Context, email string) (*user_model.User, error) {
//				panic("mock out the FindByEmail method")
//			},
//			FindByIDFunc: func(ctx context.Context, id string) (*user_model.User, error) {
//				panic("mock out the FindByID method")
//			},
//		}
//
//		// use mockedUserRepository in code that requires auth_service.UserRepository
//		// and then make assertions.
//
//	}
type UserRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, user *user_model.User) error

	// ExistsByEmailFunc mocks the ExistsByEmail method.
	ExistsByEmailFunc func(ctx context.Context, email string) (bool, error)

	// FindByEmailFunc mocks the FindByEmail method.
	FindByEmailFunc func(ctx context.Context, email string) (*user_model.User, error)

	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, id string) (*user_model.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *user_model.User
		}
		// ExistsByEmail holds details about calls to the ExistsByEmail method.
		ExistsByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// FindByEmail holds details about calls to the FindByEmail method.
		FindByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
	}
	lockCreate        sync.RWMutex
	lockExistsByEmail sync.RWMutex
	lockFindByEmail   sync.RWMutex
	lockFindByID      sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UserRepositoryMock) Create(ctx context.Context, user *user_model.User) error {
	if mock.CreateFunc == nil {
		panic("UserRepositoryMock.CreateFunc: method is nil but UserRepository.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *user_model.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserRepository.CreateCalls())
func (mock *UserRepositoryMock) CreateCalls() []struct {
	Ctx  context.Context
	User *user_model.User
} {
	var calls []struct {
		Ctx  context.Context
		User *user_model.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ExistsByEmail calls ExistsByEmailFunc.
func (mock *UserRepositoryMock) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	if mock.ExistsByEmailFunc == nil {
		panic("UserRepositoryMock.ExistsByEmailFunc: method is nil but UserRepository.ExistsByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockExistsByEmail.Lock()
	mock.calls.ExistsByEmail = append(mock.calls.ExistsByEmail, callInfo)
	mock.lockExistsByEmail.Unlock()
	return mock.ExistsByEmailFunc(ctx, email)
}

// ExistsByEmailCalls gets all the calls that were made to ExistsByEmail.
// Check the length with:
//
//	len(mockedUserRepository.ExistsByEmailCalls())
func (mock *UserRepositoryMock) ExistsByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockExistsByEmail.RLock()
	calls = mock.calls.ExistsByEmail
	mock.lockExistsByEmail.RUnlock()
	return calls
}

// FindByEmail calls FindByEmailFunc.
func (mock *UserRepositoryMock) FindByEmail(ctx context.Context, email string) (*user_model.User, error) {
	if mock.FindByEmailFunc == nil {
		panic("UserRepositoryMock.FindByEmailFunc: method is nil but UserRepository.FindByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockFindByEmail.Lock()
	mock.calls.FindByEmail = append(mock.calls.FindByEmail, callInfo)
	mock.lockFindByEmail.Unlock()
	return mock.FindByEmailFunc(ctx, email)
}

// FindByEmailCalls gets all the calls that were made to FindByEmail.
// Check the length with:
//
//	len(mockedUserRepository.FindByEmailCalls())
func (mock *UserRepositoryMock) FindByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockFindByEmail.RLock()
	calls = mock.calls.FindByEmail
	mock.lockFindByEmail.RUnlock()
	return calls
}

// FindByID calls FindByIDFunc.
func (mock *UserRepositoryMock) FindByID(ctx context.Context, id string) (*user_model.User, error) {
	if mock.FindByIDFunc == nil {
		panic("UserRepositoryMock.FindByIDFunc: method is nil but UserRepository.FindByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, id)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedUserRepository.FindByIDCalls())
func (mock *UserRepositoryMock) FindByIDCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// Ensure, that AccountRepositoryMock does implement auth_service.AccountRepository.
// If this is not the case, regenerate this file with moq.
var _ auth_service.AccountRepository = &AccountRepositoryMock{}

// AccountRepositoryMock is a mock implementation of auth_service.AccountRepository.
//
//	func TestSomethingThatUsesAccountRepository(t *testing.T) {
//
//		// make and configure a mocked auth_service.AccountRepository
//		mockedAccountRepository := &AccountRepositoryMock{
//			CreateFunc: func(ctx context.Context, account *account_model.Account) error {
//				panic("mock out the Create method")
//			},
//		}
//
//		// use mockedAccountRepository in code that requires auth_service.AccountRepository
//		// and then make assertions.
//
//	}
type AccountRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, account *account_model.Account) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Account is the account argument value.
			Account *account_model.Account
		}
	}
	lockCreate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *AccountRepositoryMock) Create(ctx context.Context, account *account_model.Account) error {
	if mock.CreateFunc == nil {
		panic("AccountRepositoryMock.CreateFunc: method is nil but AccountRepository.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Account *account_model.Account
	}{
		Ctx:     ctx,
		Account: account,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, account)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedAccountRepository.CreateCalls())
func (mock *AccountRepositoryMock) CreateCalls() []struct {
	Ctx     context.Context
	Account *account_model.Account
} {
	var calls []struct {
		Ctx     context.Context
		Account *account_model.Account
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Ensure, that SessionRepositoryMock does implement auth_service.SessionRepository.
// If this is not the case, regenerate this file with moq.
var _ auth_service.SessionRepository = &SessionRepositoryMock{}

// SessionRepositoryMock is a mock implementation of auth_service.SessionRepository.
//
//	func TestSomethingThatUsesSessionRepository(t *testing.T) {
//
//		// make and configure a mocked auth_service.SessionRepository
//		mockedSessionRepository := &SessionRepositoryMock{
//			CreateFunc: func(ctx context.Context, session *session_model.Session) error {
//				panic("mock out the Create method")
//			},
//			DeleteByRefreshTokenHashFunc: func(ctx context.Context, tokenHash string) error {
//				panic("mock out the DeleteByRefreshTokenHash method")
//			},
//			FindByRefreshTokenHashFunc: func(ctx context.Context, tokenHash string) (*session_model.Session, error) {
//				panic("mock out the FindByRefreshTokenHash method")
//			},
//		}
//
//		// use mockedSessionRepository in code that requires auth_service.SessionRepository
//		// and then make assertions.
//
//	}
type SessionRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, session *session_model.Session) error

	// DeleteByRefreshTokenHashFunc mocks the DeleteByRefreshTokenHash method.
	DeleteByRefreshTokenHashFunc func(ctx context.Context, tokenHash string) error

	// FindByRefreshTokenHashFunc mocks the FindByRefreshTokenHash method.
	FindByRefreshTokenHashFunc func(ctx context.Context, tokenHash string) (*session_model.Session, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Session is the session argument value.
			Session *session_model.Session
		}
		// DeleteByRefreshTokenHash holds details about calls to the DeleteByRefreshTokenHash method.
		DeleteByRefreshTokenHash []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TokenHash is the tokenHash argument value.
			TokenHash string
		}
		// FindByRefreshTokenHash holds details about calls to the FindByRefreshTokenHash method.
		FindByRefreshTokenHash []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TokenHash is the tokenHash argument value.
			TokenHash string
		}
	}
	lockCreate                   sync.RWMutex
	lockDeleteByRefreshTokenHash sync.RWMutex
	lockFindByRefreshTokenHash   sync.RWMutex
}

// Create calls CreateFunc.
func (mock *SessionRepositoryMock) Create(ctx context.Context, session *session_model.Session) error {
	if mock.CreateFunc == nil {
		panic("SessionRepositoryMock.CreateFunc: method is nil but SessionRepository.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Session *session_model.Session
	}{
		Ctx:     ctx,
		Session: session,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, session)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedSessionRepository.CreateCalls())
func (mock *SessionRepositoryMock) CreateCalls() []struct {
	Ctx     context.Context
	Session *session_model.Session
} {
	var calls []struct {
		Ctx     context.Context
		Session *session_model.Session
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// DeleteByRefreshTokenHash calls DeleteByRefreshTokenHashFunc.
func (mock *SessionRepositoryMock) DeleteByRefreshTokenHash(ctx context.Context, tokenHash string) error {
	if mock.DeleteByRefreshTokenHashFunc == nil {
		panic("SessionRepositoryMock.DeleteByRefreshTokenHashFunc: method is nil but SessionRepository.DeleteByRefreshTokenHash was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		TokenHash string
	}{
		Ctx:       ctx,
		TokenHash: tokenHash,
	}
	mock.lockDeleteByRefreshTokenHash.Lock()
	mock.calls.DeleteByRefreshTokenHash = append(mock.calls.DeleteByRefreshTokenHash, callInfo)
	mock.lockDeleteByRefreshTokenHash.Unlock()
	return mock.DeleteByRefreshTokenHashFunc(ctx, tokenHash)
}

// DeleteByRefreshTokenHashCalls gets all the calls that were made to DeleteByRefreshTokenHash.
// Check the length with:
//
//	len(mockedSessionRepository.DeleteByRefreshTokenHashCalls())
func (mock *SessionRepositoryMock) DeleteByRefreshTokenHashCalls() []struct {
	Ctx       context.Context
	TokenHash string
} {
	var calls []struct {
		Ctx       context.Context
		TokenHash string
	}
	mock.lockDeleteByRefreshTokenHash.RLock()
	calls = mock.calls.DeleteByRefreshTokenHash
	mock.lockDeleteByRefreshTokenHash.RUnlock()
	return calls
}

// FindByRefreshTokenHash calls FindByRefreshTokenHashFunc.
func (mock *SessionRepositoryMock) FindByRefreshTokenHash(ctx context.Context, tokenHash string) (*session_model.Session, error) {
	if mock.FindByRefreshTokenHashFunc == nil {
		panic("SessionRepositoryMock.FindByRefreshTokenHashFunc: method is nil but SessionRepository.FindByRefreshTokenHash was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		TokenHash string
	}{
		Ctx:       ctx,
		TokenHash: tokenHash,
	}
	mock.lockFindByRefreshTokenHash.Lock()
	mock.calls.FindByRefreshTokenHash = append(mock.calls.FindByRefreshTokenHash, callInfo)
	mock.lockFindByRefreshTokenHash.Unlock()
	return mock.FindByRefreshTokenHashFunc(ctx, tokenHash)
}

// FindByRefreshTokenHashCalls gets all the calls that were made to FindByRefreshTokenHash.
// Check the length with:
//
//	len(mockedSessionRepository.FindByRefreshTokenHashCalls())
func (mock *SessionRepositoryMock) FindByRefreshTokenHashCalls() []struct {
	Ctx       context.Context
	TokenHash string
} {
	var calls []struct {
		Ctx       context.Context
		TokenHash string
	}
	mock.lockFindByRefreshTokenHash.RLock()
	calls = mock.calls.FindByRefreshTokenHash
	mock.lockFindByRefreshTokenHash.RUnlock()
	return calls
}

// Ensure, that JWTManagerMock does implement auth_service.JWTManager.
// If this is not the case, regenerate this file with moq.
var _ auth_service.JWTManager = &JWTManagerMock{}

// JWTManagerMock is a mock implementation of auth_service.JWTManager.
//
//	func TestSomethingThatUsesJWTManager(t *testing.T) {
//
//		// make and configure a mocked auth_service.JWTManager
//		mockedJWTManager := &JWTManagerMock{
//			GenerateAccessTokenFunc: func(userID string, roleID int) (string, error) {
//				panic("mock out the GenerateAccessToken method")
//			},
//			GenerateRefreshTokenFunc: func() (string, error) {
//				panic("mock out the GenerateRefreshToken method")
//			},
//			RefreshTTLFunc: func() time.Duration {
//				panic("mock out the RefreshTTL method")
//			},
//		}
//
//		// use mockedJWTManager in code that requires auth_service.JWTManager
//		// and then make assertions.
//
//	}
type JWTManagerMock struct {
	// GenerateAccessTokenFunc mocks the GenerateAccessToken method.
	GenerateAccessTokenFunc func(userID string, roleID int) (string, error)

	// GenerateRefreshTokenFunc mocks the GenerateRefreshToken method.
	GenerateRefreshTokenFunc func() (string, error)

	// RefreshTTLFunc mocks the RefreshTTL method.
	RefreshTTLFunc func() time.Duration

	// calls tracks calls to the methods.
	calls struct {
		// GenerateAccessToken holds details about calls to the GenerateAccessToken method.
		GenerateAccessToken []struct {
			// UserID is the userID argument value.
			UserID string
			// RoleID is the roleID argument value.
			RoleID int
		}
		// GenerateRefreshToken holds details about calls to the GenerateRefreshToken method.
		GenerateRefreshToken []struct {
		}
		// RefreshTTL holds details about calls to the RefreshTTL method.
		RefreshTTL []struct {
		}
	}
	lockGenerateAccessToken  sync.RWMutex
	lockGenerateRefreshToken sync.RWMutex
	lockRefreshTTL           sync.RWMutex
}

// GenerateAccessToken calls GenerateAccessTokenFunc.
func (mock *JWTManagerMock) GenerateAccessToken(userID string, roleID int) (string, error) {
	if mock.GenerateAccessTokenFunc == nil {
		panic("JWTManagerMock.GenerateAccessTokenFunc: method is nil but JWTManager.GenerateAccessToken was just called")
	}
	callInfo := struct {
		UserID string
		RoleID int
	}{
		UserID: userID,
		RoleID: roleID,
	}
	mock.lockGenerateAccessToken.Lock()
	mock.calls.GenerateAccessToken = append(mock.calls.GenerateAccessToken, callInfo)
	mock.lockGenerateAccessToken.Unlock()
	return mock.GenerateAccessTokenFunc(userID, roleID)
}

// GenerateAccessTokenCalls gets all the calls that were made to GenerateAccessToken.
// Check the length with:
//
//	len(mockedJWTManager.GenerateAccessTokenCalls())
func (mock *JWTManagerMock) GenerateAccessTokenCalls() []struct {
	UserID string
	RoleID int
} {
	var calls []struct {
		UserID string
		RoleID int
	}
	mock.lockGenerateAccessToken.RLock()
	calls = mock.calls.GenerateAccessToken
	mock.lockGenerateAccessToken.RUnlock()
	return calls
}

// GenerateRefreshToken calls GenerateRefreshTokenFunc.
func (mock *JWTManagerMock) GenerateRefreshToken() (string, error) {
	if mock.GenerateRefreshTokenFunc == nil {
		panic("JWTManagerMock.GenerateRefreshTokenFunc: method is nil but JWTManager.GenerateRefreshToken was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGenerateRefreshToken.Lock()
	mock.calls.GenerateRefreshToken = append(mock.calls.GenerateRefreshToken, callInfo)
	mock.lockGenerateRefreshToken.Unlock()
	return mock.GenerateRefreshTokenFunc()
}

// GenerateRefreshTokenCalls gets all the calls that were made to GenerateRefreshToken.
// Check the length with:
//
//	len(mockedJWTManager.GenerateRefreshTokenCalls())
func (mock *JWTManagerMock) GenerateRefreshTokenCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGenerateRefreshToken.RLock()
	calls = mock.calls.GenerateRefreshToken
	mock.lockGenerateRefreshToken.RUnlock()
	return calls
}

// RefreshTTL calls RefreshTTLFunc.
func (mock *JWTManagerMock) RefreshTTL() time.Duration {
	if mock.RefreshTTLFunc == nil {
		panic("JWTManagerMock.RefreshTTLFunc: method is nil but JWTManager.RefreshTTL was just called")
	}
	callInfo := struct {
	}{}
	mock.lockRefreshTTL.Lock()
	mock.calls.RefreshTTL = append(mock.calls.RefreshTTL, callInfo)
	mock.lockRefreshTTL.Unlock()
	return mock.RefreshTTLFunc()
}

// RefreshTTLCalls gets all the calls that were made to RefreshTTL.
// Check the length with:
//
//	len(mockedJWTManager.RefreshTTLCalls())
func (mock *JWTManagerMock) RefreshTTLCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRefreshTTL.RLock()
	calls = mock.calls.RefreshTTL
	mock.lockRefreshTTL.RUnlock()
	return calls
}
