// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	account_model "user-wallet-service/internal/model/account-model"
	transaction_model "user-wallet-service/internal/model/transaction-model"
	"user-wallet-service/internal/service/account-service"
)

// Ensure, that AccountRepositoryMock does implement account_service.AccountRepository.
// If this is not the case, regenerate this file with moq.
var _ account_service.AccountRepository = &AccountRepositoryMock{}

// AccountRepositoryMock is a mock implementation of account_service.AccountRepository.
//
//	func TestSomethingThatUsesAccountRepository(t *testing.T) {
//
//		// make and configure a mocked account_service.AccountRepository
//		mockedAccountRepository := &AccountRepositoryMock{
//			FindByUserIDFunc: func(ctx context.Context, userID string) (*account_model.Account, error) {
//				panic("mock out the FindByUserID method")
//			},
//			TransferFunc: func(ctx context.Context, fromID string, toID string, amount string) error {
//				panic("mock out the Transfer method")
//			},
//			UpdateBalanceFunc: func(ctx context.Context, id string, delta string) (string, error) {
//				panic("mock out the UpdateBalance method")
//			},
//		}
//
//		// use mockedAccountRepository in code that requires account_service.AccountRepository
//		// and then make assertions.
//
//	}
type AccountRepositoryMock struct {
	// FindByUserIDFunc mocks the FindByUserID method.
	FindByUserIDFunc func(ctx context.Context, userID string) (*account_model.Account, error)

	// TransferFunc mocks the Transfer method.
	TransferFunc func(ctx context.Context, fromID string, toID string, amount string) error

	// UpdateBalanceFunc mocks the UpdateBalance method.
	UpdateBalanceFunc func(ctx context.Context, id string, delta string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindByUserID holds details about calls to the FindByUserID method.
		FindByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// Transfer holds details about calls to the Transfer method.
		Transfer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FromID is the fromID argument value.
			FromID string
			// ToID is the toID argument value.
			ToID string
			// Amount is the amount argument value.
			Amount string
		}
		// UpdateBalance holds details about calls to the UpdateBalance method.
		UpdateBalance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Delta is the delta argument value.
			Delta string
		}
	}
	lockFindByUserID  sync.RWMutex
	lockTransfer      sync.RWMutex
	lockUpdateBalance sync.RWMutex
}

// FindByUserID calls FindByUserIDFunc.
func (mock *AccountRepositoryMock) FindByUserID(ctx context.Context, userID string) (*account_model.Account, error) {
	if mock.FindByUserIDFunc == nil {
		panic("AccountRepositoryMock.FindByUserIDFunc: method is nil but AccountRepository.FindByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockFindByUserID.Lock()
	mock.calls.FindByUserID = append(mock.calls.FindByUserID, callInfo)
	mock.lockFindByUserID.Unlock()
	return mock.FindByUserIDFunc(ctx, userID)
}

// FindByUserIDCalls gets all the calls that were made to FindByUserID.
// Check the length with:
//
//	len(mockedAccountRepository.FindByUserIDCalls())
func (mock *AccountRepositoryMock) FindByUserIDCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockFindByUserID.RLock()
	calls = mock.calls.FindByUserID
	mock.lockFindByUserID.RUnlock()
	return calls
}

// Transfer calls TransferFunc.
func (mock *AccountRepositoryMock) Transfer(ctx context.Context, fromID string, toID string, amount string) error {
	if mock.TransferFunc == nil {
		panic("AccountRepositoryMock.TransferFunc: method is nil but AccountRepository.Transfer was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		FromID string
		ToID   string
		Amount string
	}{
		Ctx:    ctx,
		FromID: fromID,
		ToID:   toID,
		Amount: amount,
	}
	mock.lockTransfer.Lock()
	mock.calls.Transfer = append(mock.calls.Transfer, callInfo)
	mock.lockTransfer.Unlock()
	return mock.TransferFunc(ctx, fromID, toID, amount)
}

// TransferCalls gets all the calls that were made to Transfer.
// Check the length with:
//
//	len(mockedAccountRepository.TransferCalls())
func (mock *AccountRepositoryMock) TransferCalls() []struct {
	Ctx    context.Context
	FromID string
	ToID   string
	Amount string
} {
	var calls []struct {
		Ctx    context.Context
		FromID string
		ToID   string
		Amount string
	}
	mock.lockTransfer.RLock()
	calls = mock.calls.Transfer
	mock.lockTransfer.RUnlock()
	return calls
}

// UpdateBalance calls UpdateBalanceFunc.
func (mock *AccountRepositoryMock) UpdateBalance(ctx context.Context, id string, delta string) (string, error) {
	if mock.UpdateBalanceFunc == nil {
		panic("AccountRepositoryMock.UpdateBalanceFunc: method is nil but AccountRepository.UpdateBalance was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		ID    string
		Delta string
	}{
		Ctx:   ctx,
		ID:    id,
		Delta: delta,
	}
	mock.lockUpdateBalance.Lock()
	mock.calls.UpdateBalance = append(mock.calls.UpdateBalance, callInfo)
	mock.lockUpdateBalance.Unlock()
	return mock.UpdateBalanceFunc(ctx, id, delta)
}

// UpdateBalanceCalls gets all the calls that were made to UpdateBalance.
// Check the length with:
//
//	len(mockedAccountRepository.UpdateBalanceCalls())
func (mock *AccountRepositoryMock) UpdateBalanceCalls() []struct {
	Ctx   context.Context
	ID    string
	Delta string
} {
	var calls []struct {
		Ctx   context.Context
		ID    string
		Delta string
	}
	mock.lockUpdateBalance.RLock()
	calls = mock.calls.UpdateBalance
	mock.lockUpdateBalance.RUnlock()
	return calls
}

// Ensure, that TransactionRepositoryMock does implement account_service.TransactionRepository.
// If this is not the case, regenerate this file with moq.
var _ account_service.TransactionRepository = &TransactionRepositoryMock{}

// TransactionRepositoryMock is a mock implementation of account_service.TransactionRepository.
//
//	func TestSomethingThatUsesTransactionRepository(t *testing.T) {
//
//		// make and configure a mocked account_service.TransactionRepository
//		mockedTransactionRepository := &TransactionRepositoryMock{
//			CreateFunc: func(ctx context.Context, tx *transaction_model.Transaction) error {
//				panic("mock out the Create method")
//			},
//		}
//
//		// use mockedTransactionRepository in code that requires account_service.TransactionRepository
//		// and then make assertions.
//
//	}
type TransactionRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, tx *transaction_model.Transaction) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *transaction_model.Transaction
		}
	}
	lockCreate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *TransactionRepositoryMock) Create(ctx context.Context, tx *transaction_model.Transaction) error {
	if mock.CreateFunc == nil {
		panic("TransactionRepositoryMock.CreateFunc: method is nil but TransactionRepository.Create was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Tx  *transaction_model.Transaction
	}{
		Ctx: ctx,
		Tx:  tx,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, tx)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedTransactionRepository.CreateCalls())
func (mock *TransactionRepositoryMock) CreateCalls() []struct {
	Ctx context.Context
	Tx  *transaction_model.Transaction
} {
	var calls []struct {
		Ctx context.Context
		Tx  *transaction_model.Transaction
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}
