// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	profile_model "user-wallet-service/internal/model/profile-model"
	role_model "user-wallet-service/internal/model/role-model"
	user_model "user-wallet-service/internal/model/user-model"
	"user-wallet-service/internal/service/user-service"
)

// Ensure, that UserRepositoryMock does implement user_service.UserRepository.
// If this is not the case, regenerate this file with moq.
var _ user_service.UserRepository = &UserRepositoryMock{}

// UserRepositoryMock is a mock implementation of user_service.UserRepository.
//
//	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
//		// make and configure a mocked user_service.UserRepository
//		mockedUserRepository := &UserRepositoryMock{
//			FindByIDFunc: func(ctx context.Context, id string) (*user_model.User, error) {
//				panic("mock out the FindByID method")
//			},
//		}
//
//		// use mockedUserRepository in code that requires user_service.UserRepository
//		// and then make assertions.
//
//	}
type UserRepositoryMock struct {
	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, id string) (*user_model.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
	}
	lockFindByID sync.RWMutex
}

// FindByID calls FindByIDFunc.
func (mock *UserRepositoryMock) FindByID(ctx context.Context, id string) (*user_model.User, error) {
	if mock.FindByIDFunc == nil {
		panic("UserRepositoryMock.FindByIDFunc: method is nil but UserRepository.FindByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, id)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedUserRepository.FindByIDCalls())
func (mock *UserRepositoryMock) FindByIDCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// Ensure, that RoleRepositoryMock does implement user_service.RoleRepository.
// If this is not the case, regenerate this file with moq.
var _ user_service.RoleRepository = &RoleRepositoryMock{}

// RoleRepositoryMock is a mock implementation of user_service.RoleRepository.
//
//	func TestSomethingThatUsesRoleRepository(t *testing.T) {
//
//		// make and configure a mocked user_service.RoleRepository
//		mockedRoleRepository := &RoleRepositoryMock{
//			FindByIDFunc: func(ctx context.Context, id int) (*role_model.Role, error) {
//				panic("mock out the FindByID method")
//			},
//		}
//
//		// use mockedRoleRepository in code that requires user_service.RoleRepository
//		// and then make assertions.
//
//	}
type RoleRepositoryMock struct {
	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, id int) (*role_model.Role, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
		}
	}
	lockFindByID sync.RWMutex
}

// FindByID calls FindByIDFunc.
func (mock *RoleRepositoryMock) FindByID(ctx context.Context, id int) (*role_model.Role, error) {
	if mock.FindByIDFunc == nil {
		panic("RoleRepositoryMock.FindByIDFunc: method is nil but RoleRepository.FindByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, id)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedRoleRepository.FindByIDCalls())
func (mock *RoleRepositoryMock) FindByIDCalls() []struct {
	Ctx context.Context
	ID  int
} {
	var calls []struct {
		Ctx context.Context
		ID  int
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// Ensure, that ProfileRepositoryMock does implement user_service.ProfileRepository.
// If this is not the case, regenerate this file with moq.
var _ user_service.ProfileRepository = &ProfileRepositoryMock{}

// ProfileRepositoryMock is a mock implementation of user_service.ProfileRepository.
//
//	func TestSomethingThatUsesProfileRepository(t *testing.T) {
//
//		// make and configure a mocked user_service.ProfileRepository
//		mockedProfileRepository := &ProfileRepositoryMock{
//			FindByUserIDFunc: func(ctx context.Context, userID string) (*profile_model.Profile, error) {
//				panic("mock out the FindByUserID method")
//			},
//			UpsertFunc: func(ctx context.Context, profile *profile_model.Profile) error {
//				panic("mock out the Upsert method")
//			},
//		}
//
//		// use mockedProfileRepository in code that requires user_service.ProfileRepository
//		// and then make assertions.
//
//	}
type ProfileRepositoryMock struct {
	// FindByUserIDFunc mocks the FindByUserID method.
	FindByUserIDFunc func(ctx context.Context, userID string) (*profile_model.Profile, error)

	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(ctx context.Context, profile *profile_model.Profile) error

	// calls tracks calls to the methods.
	calls struct {
		// FindByUserID holds details about calls to the FindByUserID method.
		FindByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Profile is the profile argument value.
			Profile *profile_model.Profile
		}
	}
	lockFindByUserID sync.RWMutex
	lockUpsert       sync.RWMutex
}

// FindByUserID calls FindByUserIDFunc.
func (mock *ProfileRepositoryMock) FindByUserID(ctx context.Context, userID string) (*profile_model.Profile, error) {
	if mock.FindByUserIDFunc == nil {
		panic("ProfileRepositoryMock.FindByUserIDFunc: method is nil but ProfileRepository.FindByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockFindByUserID.Lock()
	mock.calls.FindByUserID = append(mock.calls.FindByUserID, callInfo)
	mock.lockFindByUserID.Unlock()
	return mock.FindByUserIDFunc(ctx, userID)
}

// FindByUserIDCalls gets all the calls that were made to FindByUserID.
// Check the length with:
//
//	len(mockedProfileRepository.FindByUserIDCalls())
func (mock *ProfileRepositoryMock) FindByUserIDCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockFindByUserID.RLock()
	calls = mock.calls.FindByUserID
	mock.lockFindByUserID.RUnlock()
	return calls
}

// Upsert calls UpsertFunc.
func (mock *ProfileRepositoryMock) Upsert(ctx context.Context, profile *profile_model.Profile) error {
	if mock.UpsertFunc == nil {
		panic("ProfileRepositoryMock.UpsertFunc: method is nil but ProfileRepository.Upsert was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Profile *profile_model.Profile
	}{
		Ctx:     ctx,
		Profile: profile,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	return mock.UpsertFunc(ctx, profile)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockedProfileRepository.UpsertCalls())
func (mock *ProfileRepositoryMock) UpsertCalls() []struct {
	Ctx     context.Context
	Profile *profile_model.Profile
} {
	var calls []struct {
		Ctx     context.Context
		Profile *profile_model.Profile
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}
