// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	account_model "user-wallet-service/internal/model/account-model"
	request_model "user-wallet-service/internal/model/request-model"
	transaction_model "user-wallet-service/internal/model/transaction-model"
	"user-wallet-service/internal/service/transaction-service"
)

// Ensure, that AccountRepositoryMock does implement transaction_service.AccountRepository.
// If this is not the case, regenerate this file with moq.
var _ transaction_service.AccountRepository = &AccountRepositoryMock{}

// AccountRepositoryMock is a mock implementation of transaction_service.AccountRepository.
//
//	func TestSomethingThatUsesAccountRepository(t *testing.T) {
//
//		// make and configure a mocked transaction_service.AccountRepository
//		mockedAccountRepository := &AccountRepositoryMock{
//			FindByUserIDFunc: func(ctx context.Context, userID string) (*account_model.Account, error) {
//				panic("mock out the FindByUserID method")
//			},
//		}
//
//		// use mockedAccountRepository in code that requires transaction_service.AccountRepository
//		// and then make assertions.
//
//	}
type AccountRepositoryMock struct {
	// FindByUserIDFunc mocks the FindByUserID method.
	FindByUserIDFunc func(ctx context.Context, userID string) (*account_model.Account, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindByUserID holds details about calls to the FindByUserID method.
		FindByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
	}
	lockFindByUserID sync.RWMutex
}

// FindByUserID calls FindByUserIDFunc.
func (mock *AccountRepositoryMock) FindByUserID(ctx context.Context, userID string) (*account_model.Account, error) {
	if mock.FindByUserIDFunc == nil {
		panic("AccountRepositoryMock.FindByUserIDFunc: method is nil but AccountRepository.FindByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockFindByUserID.Lock()
	mock.calls.FindByUserID = append(mock.calls.FindByUserID, callInfo)
	mock.lockFindByUserID.Unlock()
	return mock.FindByUserIDFunc(ctx, userID)
}

// FindByUserIDCalls gets all the calls that were made to FindByUserID.
// Check the length with:
//
//	len(mockedAccountRepository.FindByUserIDCalls())
func (mock *AccountRepositoryMock) FindByUserIDCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockFindByUserID.RLock()
	calls = mock.calls.FindByUserID
	mock.lockFindByUserID.RUnlock()
	return calls
}

// Ensure, that TransactionRepositoryMock does implement transaction_service.TransactionRepository.
// If this is not the case, regenerate this file with moq.
var _ transaction_service.TransactionRepository = &TransactionRepositoryMock{}

// TransactionRepositoryMock is a mock implementation of transaction_service.TransactionRepository.
//
//	func TestSomethingThatUsesTransactionRepository(t *testing.T) {
//
//		// make and configure a mocked transaction_service.TransactionRepository
//		mockedTransactionRepository := &TransactionRepositoryMock{
//			ListByAccountIDFunc: func(ctx context.Context, accountID string, filter request_model.TransactionFilter) ([]transaction_model.Transaction, int, error) {
//				panic("mock out the ListByAccountID method")
//			},
//		}
//
//		// use mockedTransactionRepository in code that requires transaction_service.TransactionRepository
//		// and then make assertions.
//
//	}
type TransactionRepositoryMock struct {
	// ListByAccountIDFunc mocks the ListByAccountID method.
	ListByAccountIDFunc func(ctx context.Context, accountID string, filter request_model.TransactionFilter) ([]transaction_model.Transaction, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListByAccountID holds details about calls to the ListByAccountID method.
		ListByAccountID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AccountID is the accountID argument value.
			AccountID string
			// Filter is the filter argument value.
			Filter request_model.TransactionFilter
		}
	}
	lockListByAccountID sync.RWMutex
}

// ListByAccountID calls ListByAccountIDFunc.
func (mock *TransactionRepositoryMock) ListByAccountID(ctx context.Context, accountID string, filter request_model.TransactionFilter) ([]transaction_model.Transaction, int, error) {
	if mock.ListByAccountIDFunc == nil {
		panic("TransactionRepositoryMock.ListByAccountIDFunc: method is nil but TransactionRepository.ListByAccountID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		AccountID string
		Filter    request_model.TransactionFilter
	}{
		Ctx:       ctx,
		AccountID: accountID,
		Filter:    filter,
	}
	mock.lockListByAccountID.Lock()
	mock.calls.ListByAccountID = append(mock.calls.ListByAccountID, callInfo)
	mock.lockListByAccountID.Unlock()
	return mock.ListByAccountIDFunc(ctx, accountID, filter)
}

// ListByAccountIDCalls gets all the calls that were made to ListByAccountID.
// Check the length with:
//
//	len(mockedTransactionRepository.ListByAccountIDCalls())
func (mock *TransactionRepositoryMock) ListByAccountIDCalls() []struct {
	Ctx       context.Context
	AccountID string
	Filter    request_model.TransactionFilter
} {
	var calls []struct {
		Ctx       context.Context
		AccountID string
		Filter    request_model.TransactionFilter
	}
	mock.lockListByAccountID.RLock()
	calls = mock.calls.ListByAccountID
	mock.lockListByAccountID.RUnlock()
	return calls
}
