// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	role_model "user-wallet-service/internal/model/role-model"
	user_model "user-wallet-service/internal/model/user-model"
	"user-wallet-service/internal/service/admin-service"
)

// Ensure, that UserRepositoryMock does implement admin_service.UserRepository.
// If this is not the case, regenerate this file with moq.
var _ admin_service.UserRepository = &UserRepositoryMock{}

// UserRepositoryMock is a mock implementation of admin_service.UserRepository.
//
//	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
//		// make and configure a mocked admin_service.UserRepository
//		mockedUserRepository := &UserRepositoryMock{
//			CountFunc: func(ctx context.Context) (int, error) {
//				panic("mock out the Count method")
//			},
//			ListFunc: func(ctx context.Context, offset int, limit int) ([]user_model.User, error) {
//				panic("mock out the List method")
//			},
//			UpdateRoleFunc: func(ctx context.Context, id string, roleID int) error {
//				panic("mock out the UpdateRole method")
//			},
//			UpdateStatusFunc: func(ctx context.Context, id string, status string) error {
//				panic("mock out the UpdateStatus method")
//			},
//		}
//
//		// use mockedUserRepository in code that requires admin_service.UserRepository
//		// and then make assertions.
//
//	}
type UserRepositoryMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context) (int, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, offset int, limit int) ([]user_model.User, error)

	// UpdateRoleFunc mocks the UpdateRole method.
	UpdateRoleFunc func(ctx context.Context, id string, roleID int) error

	// UpdateStatusFunc mocks the UpdateStatus method.
	UpdateStatusFunc func(ctx context.Context, id string, status string) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Offset is the offset argument value.
			Offset int
			// Limit is the limit argument value.
			Limit int
		}
		// UpdateRole holds details about calls to the UpdateRole method.
		UpdateRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// RoleID is the roleID argument value.
			RoleID int
		}
		// UpdateStatus holds details about calls to the UpdateStatus method.
		UpdateStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Status is the status argument value.
			Status string
		}
	}
	lockCount        sync.RWMutex
	lockList         sync.RWMutex
	lockUpdateRole   sync.RWMutex
	lockUpdateStatus sync.RWMutex
}

// Count calls CountFunc.
func (mock *UserRepositoryMock) Count(ctx context.Context) (int, error) {
	if mock.CountFunc == nil {
		panic("UserRepositoryMock.CountFunc: method is nil but UserRepository.Count was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(ctx)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedUserRepository.CountCalls())
func (mock *UserRepositoryMock) CountCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *UserRepositoryMock) List(ctx context.Context, offset int, limit int) ([]user_model.User, error) {
	if mock.ListFunc == nil {
		panic("UserRepositoryMock.ListFunc: method is nil but UserRepository.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Offset int
		Limit  int
	}{
		Ctx:    ctx,
		Offset: offset,
		Limit:  limit,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, offset, limit)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedUserRepository.ListCalls())
func (mock *UserRepositoryMock) ListCalls() []struct {
	Ctx    context.Context
	Offset int
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		Offset int
		Limit  int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// UpdateRole calls UpdateRoleFunc.
func (mock *UserRepositoryMock) UpdateRole(ctx context.Context, id string, roleID int) error {
	if mock.UpdateRoleFunc == nil {
		panic("UserRepositoryMock.UpdateRoleFunc: method is nil but UserRepository.UpdateRole was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     string
		RoleID int
	}{
		Ctx:    ctx,
		ID:     id,
		RoleID: roleID,
	}
	mock.lockUpdateRole.Lock()
	mock.calls.UpdateRole = append(mock.calls.UpdateRole, callInfo)
	mock.lockUpdateRole.Unlock()
	return mock.UpdateRoleFunc(ctx, id, roleID)
}

// UpdateRoleCalls gets all the calls that were made to UpdateRole.
// Check the length with:
//
//	len(mockedUserRepository.UpdateRoleCalls())
func (mock *UserRepositoryMock) UpdateRoleCalls() []struct {
	Ctx    context.Context
	ID     string
	RoleID int
} {
	var calls []struct {
		Ctx    context.Context
		ID     string
		RoleID int
	}
	mock.lockUpdateRole.RLock()
	calls = mock.calls.UpdateRole
	mock.lockUpdateRole.RUnlock()
	return calls
}

// UpdateStatus calls UpdateStatusFunc.
func (mock *UserRepositoryMock) UpdateStatus(ctx context.Context, id string, status string) error {
	if mock.UpdateStatusFunc == nil {
		panic("UserRepositoryMock.UpdateStatusFunc: method is nil but UserRepository.UpdateStatus was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     string
		Status string
	}{
		Ctx:    ctx,
		ID:     id,
		Status: status,
	}
	mock.lockUpdateStatus.Lock()
	mock.calls.UpdateStatus = append(mock.calls.UpdateStatus, callInfo)
	mock.lockUpdateStatus.Unlock()
	return mock.UpdateStatusFunc(ctx, id, status)
}

// UpdateStatusCalls gets all the calls that were made to UpdateStatus.
// Check the length with:
//
//	len(mockedUserRepository.UpdateStatusCalls())
func (mock *UserRepositoryMock) UpdateStatusCalls() []struct {
	Ctx    context.Context
	ID     string
	Status string
} {
	var calls []struct {
		Ctx    context.Context
		ID     string
		Status string
	}
	mock.lockUpdateStatus.RLock()
	calls = mock.calls.UpdateStatus
	mock.lockUpdateStatus.RUnlock()
	return calls
}

// Ensure, that RoleRepositoryMock does implement admin_service.RoleRepository.
// If this is not the case, regenerate this file with moq.
var _ admin_service.RoleRepository = &RoleRepositoryMock{}

// RoleRepositoryMock is a mock implementation of admin_service.RoleRepository.
//
//	func TestSomethingThatUsesRoleRepository(t *testing.T) {
//
//		// make and configure a mocked admin_service.RoleRepository
//		mockedRoleRepository := &RoleRepositoryMock{
//			ListFunc: func(ctx context.Context) ([]role_model.Role, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedRoleRepository in code that requires admin_service.RoleRepository
//		// and then make assertions.
//
//	}
type RoleRepositoryMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]role_model.Role, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockList sync.RWMutex
}

// List calls ListFunc.
func (mock *RoleRepositoryMock) List(ctx context.Context) ([]role_model.Role, error) {
	if mock.ListFunc == nil {
		panic("RoleRepositoryMock.ListFunc: method is nil but RoleRepository.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedRoleRepository.ListCalls())
func (mock *RoleRepositoryMock) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
